# Dockerfile.test
FROM node:20 AS test
WORKDIR /app

# Copia tudo que o Jest precisa
COPY package*.json tsconfig*.json jest.config.ts ./
COPY src/prisma ./prisma
COPY src ./src

RUN npm install
RUN npx prisma generate

# Rodar testes diretamente em TypeScript
CMD ["npm", "run", "test"]
